[phases.setup]
nixPkgs = ["nodejs-20_x", "npm"]

[phases.install]
cmds = ["cd giroli-store && npm install"]

[phases.build]
cmds = ["cd giroli-store && npx prisma generate", "cd giroli-store && npm run build"]

[start]
cmd = "cd giroli-store && npm start"

